name: cross

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        targets:
          - x86_64-linux-gnu
          - x86_64-linux-musl
          - x86-linux-gnu
          # - x86-linux-musl
          - aarch64-linux-musl
          - riscv64-linux-musl

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Download & Extract packages
        run: |
          curl -LO https://github.com/kassane/zig-mos-bootstrap/releases/download/0.2/zig-mos-x86_64-linux-musl-baseline.tar.xz
          tar -xf zig-mos-x86_64-linux-musl-baseline.tar.xz
          echo "$PWD/zig-mos-x86_64-linux-musl-baseline" >> $GITHUB_PATH
          sudo apt update && sudo apt install -y qemu-user-binfmt
      - name: Build Summary ${{ matrix.targets }}
        run: zig build --build-file $PWD/tests/build.zig --summary all -freference-trace -Dtarget=${{ matrix.targets }}
      - name: Run ${{ matrix.targets }}
        if: ${{ failure() }}
        run: zig build rtsan --build-file $PWD/tests/build.zig --summary all -freference-trace -Dtarget=${{ matrix.targets }}
